# Generated by Django 4.1.1 on 2022-09-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ogani", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="descricao",
        ),
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(
                height_field=270,
                null=True,
                upload_to="produtos/",
                verbose_name="Imagem",
                width_field=270,
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=5, verbose_name="Preço"
            ),
        ),
    ]
