# Generated by Django 4.1.1 on 2022-10-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogani', '0004_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='nome_categoria',
        ),
        migrations.AddField(
            model_name='banner',
            name='nome',
            field=models.CharField(max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=50, null=True, verbose_name='nome'),
        ),
    ]
