# Generated by Django 4.1.1 on 2022-10-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogani', '0008_alter_categoria_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('imagem', models.ImageField(null=True, upload_to='produtos/', verbose_name='Imagem')),
                ('nome', models.CharField(max_length=50, verbose_name='Titulo')),
                ('texto_chamada', models.CharField(max_length=200, verbose_name='texto_chamada')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
