# Generated by Django 4.1.1 on 2022-10-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogani', '0010_produto_preco_promocao_produto_promocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_promocao',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Promoção'),
        ),
    ]
