# Generated by Django 4.1.1 on 2022-10-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogani', '0011_alter_produto_preco_promocao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco_promocao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Promoção'),
        ),
    ]
