# Generated by Django 4.1.1 on 2022-10-10 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogani', '0015_alter_produto_preco_promocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(max_length='500', null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome'),
        ),
    ]
