# Generated by Django 4.1.1 on 2022-10-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogani', '0018_blog_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='corpo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
