# Generated by Django 4.1.1 on 2022-10-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogani', '0020_alter_carrinhocompra_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinhocompra',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
    ]
