# Generated by Django 4.1.1 on 2022-10-19 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogani', '0021_carrinhocompra_total'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Artigo',
        ),
    ]
