# Generated by Django 4.1.1 on 2022-10-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogani', '0022_rename_blog_artigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinhocompra',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
    ]
